import Head from 'next/head'
import { useEffect, useState } from 'react'
import { FiArrowUpRight, FiBarChart2, FiCheck, FiChevronRight, FiCode, FiDatabase, FiDownload, FiExternalLink, FiGithub, FiInstagram, FiLayers, FiLinkedin, FiMail, FiMapPin, FiMenu, FiMessageCircle, FiMonitor, FiPenTool, FiSend, FiServer, FiShield, FiX } from 'react-icons/fi'

const projects = [
  { title: 'Tuy PureFlow', eyebrow: 'Featured system', type: 'Web application', description: 'An online purified water ordering and delivery management system for distributors, operations, and business analytics.', tags: ['React.js', 'PHP', 'MySQL', 'Leaflet'], visual: 'dashboard', details: { problem: 'Distributors need one place to coordinate orders, inventory, delivery operations, and customer information.', solution: 'A role-aware web system that connects ordering, fulfillment, mapping, notifications, feedback, and analytics.', role: 'Developer, Data Analyst, UI/UX Designer, System Analyst, QA/Tester, database management, and documentation.', features: ['Online water ordering', 'Multiple distributors', 'Order, inventory, delivery, and customer management', 'Notifications, mapping and routing', 'Demand analysis and Tableau visualization'], analytics: ['Order volume analysis', 'Barangay-level analysis', 'Demand forecasting', 'Moving Average and Holt\'s Linear Exponential Smoothing', 'MAPE evaluation'] } },
  { title: 'Food Delivery App', eyebrow: 'Mobile product', type: 'Multi-role workflow', description: 'A multi-role food delivery application connecting customers, restaurants, riders, and administrators through a unified workflow.', tags: ['React Native', 'Expo', 'Node.js', 'MySQL'], visual: 'mobile', details: { problem: 'A delivery workflow needs clear hand-offs between customers, restaurants, riders, and administrators.', solution: 'A mobile-first ordering experience with distinct role workflows from browsing to delivery.', role: 'Development, interface design, system analysis, API integration, and testing across role-based flows.', features: ['Restaurant browsing and ordering', 'Cart and checkout', 'Restaurant and rider workflows', 'Order management', 'Admin dashboard'] } },
  { title: 'Balmari Design & Construction', eyebrow: 'OJT project', type: 'Business website', description: 'A professional business website with service presentation and an administrative content management system.', tags: ['HTML', 'PHP', 'MySQL', 'Bootstrap'], visual: 'website', details: { problem: 'A growing design and construction company needed a polished web presence and manageable project content.', solution: 'A responsive business website paired with an admin dashboard for content and user operations.', role: 'Website planning, UI/UX, CMS development, database planning, revisions, deployment, and documentation.', features: ['Business landing page', 'Services, projects, details, about and contact', 'Carousel and CMS management', 'User management and activity logs'] } },
  { title: 'GarbageLink', eyebrow: 'Academic project', type: 'Location-based system', description: 'A waste collection route planning and location-based system.', tags: ['System analysis', 'Mapping', 'Database'], visual: 'route' },
  { title: 'WALIS', eyebrow: 'Academic project', type: 'Data management', description: 'A waste management and data management system.', tags: ['Data management', 'Documentation', 'Testing'], visual: 'table' },
  { title: 'CoopFund', eyebrow: 'Academic project', type: 'Management system', description: 'A savings and loan management system.', tags: ['Database', 'Web development', 'QA'], visual: 'finance' }
]

const skillGroups = [
  ['Web & Software Development', ['HTML', 'CSS', 'JavaScript', 'React.js', 'Next.js', 'PHP', 'Node.js', 'Express.js', 'Tailwind CSS', 'Bootstrap', 'REST API development', 'API integration', 'Responsive web development', 'Full-stack web development']],
  ['Mobile Development', ['React Native', 'Expo', 'Expo Router', 'TypeScript / TSX', 'EAS Build', 'Multi-role mobile application development', 'Mobile UI development']],
  ['Data Analytics & Business Intelligence', ['SQL', 'MySQL', 'Data cleaning', 'Data analysis', 'Data visualization', 'Business analytics', 'Dashboard development', 'Trend analysis', 'Order/sales analysis', 'Demand analysis', 'Forecasting', 'Moving Average', "Holt's Linear Exponential Smoothing", 'MAPE evaluation', 'Tableau', 'Excel']],
  ['Database & Backend', ['MySQL', 'MariaDB', 'phpMyAdmin', 'Database design', 'Database management', 'Relational database concepts', 'CRUD operations', 'PHP backend development', 'REST APIs', 'Authentication', 'Data modeling']],
  ['UI/UX Design', ['Figma', 'Wireframing', 'Prototyping', 'User-centered design', 'Responsive design', 'Interface design', 'Dashboard design', 'Design systems']],
  ['System Analysis & Business Analysis', ['Requirements analysis', 'System analysis', 'Business process analysis', 'System design', 'Process modeling', 'Technical documentation', 'Database planning', 'Translating business requirements into system features', 'Problem solving']],
  ['APIs, Maps & Integration', ['Leaflet', 'OpenStreetMap', 'OSRM Routing', 'Google Maps-related integration', 'Mapping/location features', 'Routing', 'Third-party API integration']],
  ['Deployment & Development Tools', ['Git', 'GitHub', 'Vercel', 'Hostinger', 'VS Code', 'XAMPP', 'npm', 'Expo/EAS', 'phpMyAdmin', 'draw.io', 'Chart.js']],
  ['Professional / General Skills', ['Project management', 'Technical documentation', 'Research', 'Competitor analysis', 'Problem solving', 'Analytical thinking', 'UI/UX thinking', 'Team collaboration', 'System troubleshooting']]
]

function Section({ number, title, children, id, intro }) { return <section id={id} className="section-wrap"><div className="section-kicker"><span>{number}</span><span>{title}</span></div>{intro && <p className="section-intro">{intro}</p>}{children}</section> }
function Visual({ kind = 'dashboard' }) { return <div className={`project-visual visual-${kind}`}><div className="visual-top"><span className="live-dot" /> SAMPLE DATA <span className="visual-dots">•••</span></div>{kind === 'mobile' ? <div className="phone"><div className="phone-line" /><div className="phone-item" /><div className="phone-item short" /><div className="phone-button" /></div> : <><div className="chart-bars"><i /><i /><i /><i /><i /><i /><i /></div><div className="visual-stat"><span>{kind === 'website' ? 'CMS / SYSTEM' : 'INSIGHT / FLOW'}</span><b><FiArrowUpRight /></b></div><div className="visual-grid" /></>}</div> }
function Socials() { return <div className="socials"><a href="https://github.com/RcCola2112" aria-label="GitHub"><FiGithub /></a><a href="https://www.linkedin.com" aria-label="LinkedIn placeholder"><FiLinkedin /></a><a href="mailto:denvermartinez2112@gmail.com" aria-label="Email"><FiMail /></a><a href="https://web.facebook.com/RcRoxas2112/" aria-label="Facebook">f</a><a href="https://www.instagram.com/denvermartinezroxas/" aria-label="Instagram"><FiInstagram /></a></div> }
function GithubStack() {
  const fallbackLanguages = [{ name: 'JavaScript', percentage: 32 }, { name: 'PHP', percentage: 25 }, { name: 'HTML', percentage: 18 }, { name: 'CSS', percentage: 12 }, { name: 'TypeScript', percentage: 8 }, { name: 'SQL', percentage: 5 }]
  const [stack, setStack] = useState({ languages: fallbackLanguages, repositoryCount: null, fallback: true })
  useEffect(() => { fetch('/api/github-languages').then(response => response.json()).then(setStack).catch(() => {}) }, [])
  return <div className="github-panel"><div className="github-panel-head"><span><FiGithub /> github.com/RcCola2112</span><span className="panel-status">{stack.fallback ? 'cached view' : 'live data'}</span></div><div className="github-panel-title"><div><small>PUBLIC REPOSITORIES</small><b>{stack.repositoryCount ?? '—'}</b></div><span>Languages across<br />all repositories</span></div><div className="language-bars">{stack.languages.map((language, index) => <div className="language-row" key={language.name}><div className="language-label"><span><i className={`language-dot dot-${index}`} />{language.name}</span><b>{language.percentage}%</b></div><div className="language-track"><i style={{ width: `${Math.max(language.percentage, 3)}%` }} /></div></div>)}</div><a className="github-panel-link" href="https://github.com/RcCola2112" target="_blank" rel="noreferrer">View all repositories <FiArrowUpRight /></a></div>
}

export default function Home() {
  const [menu, setMenu] = useState(false)
  const [selected, setSelected] = useState(null)
  return <>
    <Head><title>John Rc Denver M. Roxas | IT Graduate & Business Analytics</title><meta name="description" content="Portfolio of John Rc Denver M. Roxas, an IT graduate specializing in Business Analytics, web and mobile development, data analytics, system analysis, UI/UX, and software testing." /><meta name="viewport" content="width=device-width,initial-scale=1" /><meta name="theme-color" content="#08111f" /><meta property="og:title" content="John Rc Denver M. Roxas | IT Graduate & Business Analytics" /><meta property="og:description" content="IT Graduate | Business Analytics | Web & Mobile Developer" /></Head>
    <header className="nav"><a className="brand" href="#home"><span>JR</span><strong>Denver<span>.</span></strong></a><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">{menu ? <FiX /> : <FiMenu />}</button><nav className={menu ? 'nav-links open' : 'nav-links'}>{['About', 'Skills', 'Experience', 'Projects', 'Analytics', 'Education', 'Resume', 'Contact'].map((item, index) => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenu(false)}><small>{String(index + 1).padStart(2, '0')}</small>{item}</a>)}</nav><a className="nav-cta" href="#contact">Let&apos;s talk <FiArrowUpRight /></a></header>
    <main id="home">
      <section className="hero section-wrap"><div className="hero-copy"><p className="eyebrow"><span className="pulse" /> Available for entry-level opportunities</p><h1>Hi, I&apos;m <em>John Rc Denver</em> M. Roxas.</h1><p className="hero-title">IT Graduate <b>/</b> Business Analytics <b>/</b> Web &amp; Mobile Developer</p><p className="hero-text">I&apos;m a fresh IT graduate specializing in Business Analytics with hands-on experience in web and mobile development, data analytics, UI/UX design, system analysis, database management, and software testing.</p><div className="hero-actions"><a className="button primary" href="#projects">View my projects <FiArrowUpRight /></a><a className="button outline" href="/resume.pdf" download>Download resume <FiDownload /></a></div><Socials /></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><GithubStack /></div></section>
      <Section number="01" title="About" id="about" intro="I understand technology, but I also understand the business and data behind it."><div className="about-grid"><div><h2>Building useful systems<br /><span>from the whole picture.</span></h2></div><div className="about-copy"><p>I am a Bachelor of Science in Information Technology graduate specializing in Business Analytics. My practical experience spans web development, mobile development, data analytics, business analysis, UI/UX design, system analysis, database management, API integration, technical documentation, and software testing.</p><p>I enjoy turning requirements and data into practical, user-centered technology solutions: understanding the problem, designing the flow, building the system, and checking that it works as intended.</p><div className="about-points"><span><FiCheck /> Development</span><span><FiCheck /> Business analysis</span><span><FiCheck /> Data &amp; insights</span><span><FiCheck /> Quality assurance</span></div></div></div></Section>
      <Section number="02" title="Skills" id="skills" intro="A practical toolkit across development, analysis, design, and quality. No artificial percentages, just the areas I work in."><div className="skills-grid">{skillGroups.map(([name, list], index) => <article className="skill-card" key={name}><div className="skill-title"><span>0{index + 1}</span><h3>{name}</h3></div><div className="tags">{list.map(skill => <span key={skill}>{skill}</span>)}</div></article>)}</div></Section>
      <Section number="03" title="Experience" id="experience" intro="Practical academic, capstone, and OJT experience, grounded in real project workflows."><div className="timeline"><div className="timeline-marker">2026<br /><span>OJT</span></div><div className="timeline-content"><p className="eyebrow">IT Intern / OJT</p><h2>Learning the full product workflow.</h2><p>Contributed to website planning and development, UI/UX design, database planning, admin dashboard and CMS functionality, user management, activity logs, competitor research, technical documentation, system revisions, and deployment.</p><div className="timeline-projects"><div><b>Balmari Design &amp; Construction Website</b><span>Business website with administrative CMS functionality.</span></div><div><b>Food Delivery Application</b><span>Customer, restaurant, rider, and admin workflows.</span></div></div></div></div></Section>
      <Section number="04" title="Projects" id="projects" intro="Selected work that shows how development, business context, data, and quality fit together."><div className="project-grid">{projects.map((project, index) => <article className={index === 0 ? 'project-card featured' : 'project-card'} key={project.title} onClick={() => setSelected(project)}><Visual kind={project.visual} /><div className="project-content"><div className="project-meta"><span>{project.eyebrow}</span><FiArrowUpRight /></div><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><button className="text-button">View case study <FiChevronRight /></button></div></article>)}</div></Section>
      <Section number="05" title="Analytics" id="analytics" intro="I use data to identify trends, understand business processes, generate insights, and support better decision-making."><div className="analytics-layout"><div className="analytics-copy"><p className="eyebrow">Data &amp; Business Analytics</p><h2>From raw records<br /><span>to clear direction.</span></h2><p>My analytics work includes data analysis, SQL, data visualization, business intelligence, forecasting, reporting, and dashboard development.</p><div className="analytics-list"><span><FiDatabase /> Data analysis &amp; SQL</span><span><FiBarChart2 /> Visualization &amp; reporting</span><span><FiLayers /> Forecasting &amp; dashboards</span></div></div><div className="analytics-board"><div className="board-head"><span><b>Analytics overview</b><small>Sample Data</small></span><FiMore /></div><div className="kpis"><div><small>ORDER VOLUME</small><b>Trend view</b><span className="up">↗ illustrative</span></div><div><small>DATA QUALITY</small><b>Checked</b><span>validation pass</span></div></div><div className="big-chart"><div className="y-labels"><span>100</span><span>50</span><span>0</span></div><svg viewBox="0 0 600 160" preserveAspectRatio="none"><path className="chart-fill" d="M0 130 C70 118 65 80 125 96 S190 110 240 65 S290 90 340 75 S405 36 455 58 S520 20 600 30 L600 160 L0 160Z" /><path d="M0 130 C70 118 65 80 125 96 S190 110 240 65 S290 90 340 75 S405 36 455 58 S520 20 600 30" /></svg></div><div className="board-foot"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Sample visualization only</span></div></div></div></Section>
      <Section number="07" title="Education" id="education"><div className="education"><div className="edu-icon"><FiMonitor /></div><div><p className="eyebrow">Graduate</p><h2>Bachelor of Science in Information Technology</h2><p>Major / Focus: <b>Business Analytics</b></p><p>Batangas State University – ARASOF-Nasugbu</p></div><span className="edu-year">BSIT</span></div></Section>
      <Section number="08" title="Certifications" id="certifications"><div className="cert-grid"><article className="certificate-card"><div className="certificate-icon"><FiCheck /></div><div className="certificate-info"><p className="eyebrow">Certificate</p><h3>Microsoft Word Certificate</h3><p>Certificate document available for review.</p><div className="certificate-actions"><a className="button primary" href="/certificates/microsoft-word-certificate.pdf" target="_blank" rel="noreferrer">View certificate <FiExternalLink /></a><a className="button outline" href="/certificates/microsoft-word-certificate.pdf" download>Download <FiDownload /></a></div></div></article><article className="certificate-card"><div className="certificate-icon"><FiBarChart2 /></div><div className="certificate-info"><p className="eyebrow">Certificate</p><h3>Data Analytics Certificate</h3><p>Certificate document available for review.</p><div className="certificate-actions"><a className="button primary" href="/certificates/data-analytics-certificate.pdf" target="_blank" rel="noreferrer">View certificate <FiExternalLink /></a><a className="button outline" href="/certificates/data-analytics-certificate.pdf" download>Download <FiDownload /></a></div></div></article></div></Section>
      <Section number="09" title="Resume" id="resume"><div className="resume-band"><div><p className="eyebrow">A closer look</p><h2>Interested in learning more about my background?</h2></div><div className="resume-actions"><a className="button primary" href="/resume.pdf" download>Download resume <FiDownload /></a><a className="button outline" href="/resume.pdf" target="_blank" rel="noreferrer">View resume <FiExternalLink /></a></div></div></Section>
      <Section number="10" title="Contact" id="contact"><div className="contact-grid"><div><h2>Let&apos;s <span>connect.</span></h2><p>I&apos;m currently open to entry-level opportunities in web development, data analytics, business analysis, business intelligence, QA, and other IT-related roles.</p><div className="contact-details"><a href="mailto:denvermartinez2112@gmail.com"><FiMail /> denvermartinez2112@gmail.com</a><span><FiMapPin /> Philippines</span><a href="https://github.com/RcCola2112"><FiGithub /> github.com/RcCola2112</a></div></div><form className="contact-form" onSubmit={event => event.preventDefault()}><label>Name<input name="name" type="text" placeholder="Your name" required /></label><label>Email<input name="email" type="email" placeholder="you@example.com" required /></label><label>Message<textarea name="message" placeholder="Tell me a little about your opportunity..." rows="4" required /></label><button className="button primary" type="submit">Send message <FiSend /></button></form></div></Section>
    </main>
    <footer className="footer"><div><a className="brand" href="#home"><span>JR</span><strong>Denver<span>.</span></strong></a><p>IT Graduate / Business Analytics / Web &amp; Mobile Developer</p></div><Socials /><p>© 2026 John Rc Denver M. Roxas. All rights reserved.</p></footer>
    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="project-modal" onClick={event => event.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close project details"><FiX /></button><Visual kind={selected.visual} /><p className="eyebrow">{selected.eyebrow} / {selected.type}</p><h2>{selected.title}</h2><p>{selected.description}</p><div className="modal-columns"><div><h3>Overview</h3><p>{selected.details?.solution || selected.description}</p><h3>My role</h3><p>{selected.details?.role || 'Project development, analysis, documentation, and testing.'}</p></div><div><h3>Key features</h3><ul>{(selected.details?.features || selected.tags).map(item => <li key={item}><FiCheck /> {item}</li>)}</ul>{selected.details?.analytics && <><h3>Analytics</h3><ul>{selected.details.analytics.map(item => <li key={item}><FiBarChart2 /> {item}</li>)}</ul></>}</div></div><div className="modal-links"><a className="button outline" href="https://github.com/RcCola2112" target="_blank" rel="noreferrer"><FiGithub /> GitHub</a>{selected.title === 'Tuy PureFlow' ? <a className="button primary" href="https://tuypureflow.com" target="_blank" rel="noreferrer">View project <FiExternalLink /></a> : <span className="button outline unavailable">Project link unavailable</span>}</div></div></div>}
  </>
}

function FiMore() { return <span className="more-icon">•••</span> }
